### ISSUE TITLE
[Question] Handling Preview Data

### ISSUE THREAD

**Issue by savage7** [quickbirdstudios/XUI#4]
I'm already a fan of what you described as MVVM ViewState (using AnyViewModel for some time) :smiley:, but now you created XUI :heart_eyes:
The ability to use a protocol for ViewModels makes this so much nicer.

What I like most about this, is that it makes defining test data for previews so nice. For ViewState I created this MockViewModel:

```
class MockViewModel<State, Input>: BaseViewModel, ViewModel {
    @Published
    private(set) var state: State

    init(state: State) {
        self.state = state
    }

    func trigger(_: Input) {}
}
```

This way I can easily define my preview likes this:
```
let state = MenuViewState(menuEntries: menuEntries, apps: apps)
let viewModel = AnyViewModel(MockViewModel<MenuViewState, MenuViewInput>(state: state))
MenuView(viewModel: viewModel)
```
The nice thing is that I can just create a state object and fill the data in the preview code. No additional implementation is needed and the View is completely separated from the business logic code.

**My question:**
Defining ViewModels as protocols seams so much cleaner than using AnyViewModel but I cannot find a nice solution to define testdata which this approach.

How do you solve this this with ViewModels defined as protocols? 
Do you manually create a Mock implementation for every ViewModel you use in your previews?
Do you generate them?

**Comment by pauljohanneskraft** [comment]
Hey @savage7 ! Glad you like our approach and we can help with this library 😊 

I agree that for this use case it is probably easier to use ViewState MVVM rather than protocols. Since you specify the protocols yourself, your viewModel implementations will also need to conform to your protocols, which makes it hard to create generic mock implementations.

Depending on your design/development process you may already have a viewModel implementation when designing your views that you can then use. For access to Model services (e.g. database, network calls, algorithms), you could mock these services instead and use your regular viewModel implementation - but that simply depends on how you approach your view creation process.

If you find a nice solution to this issue, feel free to share here - we would be very interested in a solution as well!

**Comment by savage7** [comment]
I tried to generate the Mock Implementation with SwiftMockey and Cuckoo, both face the problem that the generated code misses the ObservableObject implementation. So a custom template would probable be more appropriate. Still the solution is not perfect...
